root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
bin = "tmp/main"
full_bin = "tmp/main"
cmd = "go build -o tmp/main main.go wire_gen.go"
delay = 1000
exclude_dir = ["assets", "vendor", "testdata"]
include_ext = ["go", "tpl", "tmpl", "html"]

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
level = "debug"
main_only = false
silent = false
time = true

[misc]
clean_on_exit = false

[proxy]
app_port = 0
enabled = false
proxy_port = 0

[screen]
clear_on_rebuild = false
keep_scroll = true
