services:
  db:
    container_name: mysql_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - .:/app
      - ./mysql/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:  # MySQL が起動完了するまで待機する設定
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: go_app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:  #`condition: service_healthy` を追加して DB が完全に起動するまで待つ
        condition: service_healthy
    environment:
      - DB_HOST=mysql_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydb

volumes:
  mysql_data:
