// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"api-project/controllers"
	"api-project/database"
	"api-project/repository"
	"api-project/service"
)

// Injectors from wire.go:

// InitializeApp は DI で UserController を生成する
func InitializeApp() (*controllers.UserController, error) {
	db, err := database.NewDatabase()
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userController := controllers.NewUserController(userService)
	return userController, nil
}
