// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"api-project/controllers"
	"api-project/database"
	"api-project/di"
	"api-project/repository"
	"api-project/service"
)

// Injectors from wire.go:

// InitializeApp は DI で AppControllers を生成する
func InitializeApp() (*di.AppControllers, error) {
	db, err := database.NewDatabase()
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userController := controllers.NewUserController(userService)
	memoRepository := repository.NewMemoRepository(db)
	memoService := service.NewMemoService(memoRepository)
	memoController := controllers.NewMemoController(memoService)
	appControllers := &di.AppControllers{
		UserController: userController,
		MemoController: memoController,
	}
	return appControllers, nil
}
